<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
        <OutputType>Library</OutputType>
        <UseWinUI>true</UseWinUI>
        <WinUISDKReferences>false</WinUISDKReferences>
        <Platforms>ARM64;x64;x86</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>wows_ime.Pages</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\wows-ime.Core\wows-ime.Core.csproj" />
        <PackageReference Include="CommunityToolkit.WinUI.Controls.SettingsControls" Version="8.2.251219" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="2.4.0" />
    </ItemGroup>
</Project>
